### PR TITLE
Add `foam-docs` type front matter do documentation notes

### PR DESCRIPTION
**Pull request by MrCordeiro**
Hello! Foam has received a lot of cool new features since I last contributed and I notice the template documentation is much richer. Well done, everyone!

I've added the `type: foam-docs` to the documentation notes so that people can more easily filter them out when they want to visualize their graphs.

@riccardoferretti, let me know what you think?

Cheers!

### CODE REVIEW

**Comment by riccardoferretti** [comment]
Hi @MrCordeiro thanks for taking the time on this.
I am hesitant to tag all the docs with the type, as I feel that the best way to filter the docs would be to exclude the folder altogether.
I think what you are describing is more due to limitations in the graph (no filtering by path) than in the docs themselves.
I understand what you are trying to do, and as an individual decision it sounds like a good workaround.

Let me know what you think

**Comment by MrCordeiro** [comment]
Hey @riccardoferretti, thanks for your response.

I get why you're not sure about the ~~tag~~ type idea. Sure, making the graph better is the ultimate fix. But, why not do something that helps people now?

Let me try to convince you with some pros:

- Quick Win: The tag is a fast and easy way for users to clean up their graphs right away.
- More Choices: With the ~~tag~~ type, you can pick what you want to see or hide. You can't do that if you just ditch the whole folder.
- Easy Access: Keeping the folder means folks can find the docs super easily when they need them.
- Low downside: I can see only one con of adding the tags, which is a small learning curve to understand why they are there. But other than that, it works rather well and it doesn't mess with the other tools.

My suggestion is to use the ~~tag~~ type for now and work on the graph for later. What do you think?

**Comment by riccardoferretti** [comment]
I understand what you are saying, I should point out that your PR is changing the type of the note, it's not adding a tag to it.

I agree with what you are saying, I guess my biggest "concern" is that this is a very specific concern and I wonder how widely it really applies.
What you are saying about the tags though it true enough, I would consider it for them (but not for the note type).

**Comment by MrCordeiro** [comment]
Sorry, when I wrote "tag", I meant "type" (I've amended my previous comment).

The whole point of using "type" in the front matter is indeed to allow more refined filtering in the Foam graph. Is my understanding incorrect? I tried the tag route, but Foam Graph's current limitations make that ineffective.

The Graph doesn't allow filtering for individual tags (you can either show them all or no tags at all) nor the notes associated with a given tag (the tags disappear, but the notes not created by the user do not).

You mentioned concern about how broadly this applies. Well, any Foam user who uses the graph view would benefit from this more nuanced filtering. Plus, it would pave the way for even more types to be used for other kinds of notes in the future.

Are there downsides to switching up the note type that I'm not seeing? Because from my perspective, the potential cons seem pretty minimal, and the benefits are immediate and pretty useful for users.

**Pull request closed without merging**
