### PR TITLE
Add Jekyll and Docker support!

### PR DESCRIPTION
**Pull request by pourmand1376**
Hi, I added some files to make this theme a ready-to-publish github website. A published website is available [Here](https://pourmand1376.github.io/foam-template/).

I also added `docker` support. So, If you want to build the website locally, first you need to install `docker`. After that you just need two commands:
```
bin/docker_build.sh
```
This command builds an image which contains jekyll binaries and required gem packages. 
```
bin/docker_run.sh
```
This commands runs the website in the local machine! That's it. No more complicated setups of jekyll and ruby and every other dependencies. 

But probably, I should split this pull request into two different pull requests. One for adding jekyll and one for adding support for docker. I will do it if you want.

### CODE REVIEW

**Comment by riccardoferretti** [comment]
hi @pourmand1376, thanks for suggesting this improvement!
First of all, I like the idea, let's see how to package it the right way.
I would like the repo to be as simple as possible, and not leak too much that is not about the notes.
Therefore I wonder whether we should have all your files (and possibly even move some of the existing files that are concerned with publishing and not notes) into a specific folder.

To make it as unintrusive as possible, we could use `/.foam/publish`, otherwise just `/publish`.
Of course the setup would still need to work with github pages.
What's your thinking about all of this?

**Comment by pourmand1376** [comment]
Hi, Thanks for the quick follow-up. I like the idea of getting rid of files that the user doesn't care. 
I moved 4 files to `/publish` folder, however they could be moved anywhere you like them to be. 

I do think that moving `Gemfile` could potentially cause some problems. Specially if users intend to host their website on `netlify` or other services, but I do not see any problem for github pages for the time being. I have to test it for netlify.

For `.gitignore` file, I searched and found [this StackOverflow question](https://stackoverflow.com/questions/44500887/is-it-possible-to-relocate-gitignore-file-itself) which says it is possible. However, we can not do it in any directory we want, just some directories. 

For `_config.yml`, I don't think this is easily possible. Even if it could be, the installation would not be as simple.

**Comment by riccardoferretti** [comment]
> I moved 4 files to /publish folder, however they could be moved anywhere you like them to be.

That's great!

> I do think that moving Gemfile could potentially cause some problems. Specially if users intend to host their website on netlify or other services, but I do not see any problem for github pages for the time being. I have to test it for netlify.

Would love to know whether that is possible and the consequences.
Is the issue you are describing with the container deployment, or with Github Pages? Could it be part of the deployment script?
With this PR I think we should at least be backwards compatible (that is, being compatible out of the box with Github Pages), and allow for quick local deployment. For other setups it might be ok to have people customize their repo.

> For .gitignore file...

`.gitignore` works in the root, not a problem

> For _config.yml, I don't think this is easily possible. Even if it could be, the installation would not be as simple

Same questions here that I have for the Gemfile above.

**Comment by pourmand1376** [comment]
Hi, Sorry for the delay. 
I tested in the `netlify` and `Gemfile` is having problems. So, we have to move it to the main directory. Actually, I think `Github pages` doesn't care about `Gemfile`. It just uses its own predefined preinstalled libraries. But, other services like netlify or vercel do care about that. This is the error I am getting from `Netlify`.
gem_file

I also tested `_config.yml` and it will have problems if we move it somewhere else (even in `github pages`).

By the way, moving docker files wouldn't make any problems. It would just work.

**Comment by pourmand1376** [comment]
I just added `GitHub Actions` to build a docker image automatically after each commit. It means that first `GitHub` will fetch the repo and install all required dependencies in a docker image. Then it will push it to [this](https://hub.docker.com/r/amirpourmand/foam-template) repo. 

image


So, to put it in a nutshell, now we can remove the old way of building the image and just tell people to:

```
docker pull amirpourmand/foam-template
```
> This command is working now since I have added its CI action to my github pages. It does have your repo as a docker image.

and then
```
docker run --rm -v "$PWD:/srv/jekyll/" -p "8080:8080" \
                    -it amirpourmand/foam-template bundler  \
                    exec jekyll serve --watch --port=8080 --host=0.0.0.0  
```
This way, we minimize the error since people do not have to build the image themselves. 

However, currently, I've uploaded the images to [my repo](https://hub.docker.com/u/amirpourmand). It is up to you to decide if you want to upload your image to my repo or create your own repo. If you choose to use mine, I can add you to collaborators so you have complete access.

By the way, to make this usable, you have to add two variables to your `github secrets`. A Tutorial is available [here](https://medium.com/platformer-blog/lets-publish-a-docker-image-to-docker-hub-using-a-github-action-f0b17e5cceb3). You can also change the image repository easily in the `deploy-image.yml` file. 

> Variable names in the secret are `DOCKER_USERNAME` and `DOCKER_PASSWORD`.

**Comment by riccardoferretti** [comment]
Thanks for all of this! 
As I am not super versed in Docker I will need some time to review the wrap my head around the whole thing, but I just wanted to let you know it's on  my radar :)

For security reasons Foam should have its own repo.
Also, I believe the deployment options should at this point be documented (kinda like what you wrote here) so that users will understand what's available and how to use it, what do you think?

**Comment by pourmand1376** [comment]
Thanks for suggestions. 

I waited until I get some time to finish this task. But, I am busy at the moment. I will take care of this ASAP.

**Comment by pourmand1376** [comment]
I added some documentation! I hope that's clear.

**Pull request closed without merging**
