### PR TITLE
Exclude node_modules #15

### PR DESCRIPTION
**Pull request by Thiruppathi**

### CODE REVIEW

**Comment by Thiruppathi** [comment]
Excluded `node_modules` for better performance. 🚀

**Comment by Thiruppathi** [comment]
@jevakallio 
Hi, 
Can you please have a look at this?  :)

**Review by jevakallio — APPROVED** [review]
LGTM! @Thiruppathi I added an additional setting to also skip the files during watcher mode.

**Comment by Thiruppathi** [comment]
@jevakallio Thanks.

**Pull request merged**
